# Generated by Django 5.0.6 on 2024-06-24 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestant_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('is_timed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rodeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodeo_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContestRodeoSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodeo.contestant')),
                ('rodeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodeo.rodeo')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodeo.series')),
            ],
        ),
        migrations.CreateModel(
            name='ContestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_rodeo_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodeo.contestrodeoseries')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodeo.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodeo.contestevent')),
                ('partner_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_one', to='rodeo.contestant')),
                ('partner_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_two', to='rodeo.contestant')),
            ],
        ),
        migrations.CreateModel(
            name='MensBreakaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb_number', models.IntegerField()),
                ('contest_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodeo.contestevent')),
            ],
        ),
        migrations.AddConstraint(
            model_name='eventpartner',
            constraint=models.CheckConstraint(check=models.Q(('partner_one', models.F('partner_two')), _negated=True), name='check_different_partners'),
        ),
        migrations.AlterUniqueTogether(
            name='contestrodeoseries',
            unique_together={('contestant', 'rodeo', 'series')},
        ),
    ]
