# Generated by Django 5.0.6 on 2024-06-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodeo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
