# Generated by Django 5.0.6 on 2024-06-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodeo', '0002_alter_event_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='contestant_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
